"""Table and summary of the support-credited corpus-B zone classification.

TOPO-029: reads `zone_labels_b.csv` (id, class, confidence, note — labelled
by eye against `ZONE_CRITERIA_B.md`, declared before labelling) and
`zones_png_b/zones_meta.json` (provenance of every credited zone), refuses to
run on an incomplete labelling, and writes `ZONES_SUPPORT_B.md`: per-class
shares (all credited zones and the top-N subset separately), the full table,
and the summary sentence — generated by the same code as the table
(PROTOCOL §8; the wave-2 stale-sentence lesson).

Usage (from pipeline/real_errors/):
    python summarize_zones_b.py --labels zone_labels_b.csv \
        --meta ../../output/topo/real_paris4/zones_png_b/zones_meta.json \
        --n-zones 178 --out ZONES_SUPPORT_B.md
"""

import argparse
import csv
import json

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

CLASSES = ('real_error', 'banner_edge', 'epoch_drift', 'false_alarm')
EN = {'real_error': 'genuine tracing error',
      'banner_edge': 'edge of the reference sector',
      'epoch_drift': 'epoch-fitting systematics',
      'false_alarm': 'false alarm'}


def note_of(row):
    """The English reading of a by-eye note.

    `note` is the observation as the labeller wrote it at labelling time and
    is never rewritten; `note_en` is its English rendering, added later as a
    separate column. Tables render `note_en` only — a missing rendering stops
    the run, so the shipped English table cannot silently pick up a Russian
    cell from a half-labelled round.
    """
    text = (row.get('note_en') or '').strip()
    if not text:
        raise SystemExit(f"note_en missing for zone {row['id']} — every row "
                         f"needs an English note before the table is written")
    return text


def shares(rows):
    n = len(rows)
    counts = {c: sum(1 for r in rows if r['class'] == c) for c in CLASSES}
    low = {c: sum(1 for r in rows
                  if r['class'] == c and r['confidence'] == 'low')
           for c in CLASSES}
    return n, counts, low


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--labels', required=True)
    parser.add_argument('--meta', required=True)
    parser.add_argument('--n-zones', type=int, required=True,
                        help='N of the corpus (top-N recall subset boundary)')
    parser.add_argument('--out', required=True)
    args = parser.parse_args()

    with open(args.meta, encoding='utf-8') as f:
        meta = json.load(f)
    with open(args.labels, encoding='utf-8-sig', newline='') as f:
        labels = {row['id']: row for row in csv.DictReader(f)}

    missing = sorted(set(meta) - set(labels))
    extra = sorted(set(labels) - set(meta))
    if missing or extra:
        raise SystemExit(f'labelling incomplete: missing {missing[:5]}... '
                         f'({len(missing)}), extra {extra}')
    bad = {i: r['class'] for i, r in labels.items()
           if r['class'] not in CLASSES}
    if bad:
        raise SystemExit(f'unknown classes: {bad}')

    all_rows = list(labels.values())
    # Census zones (TOPO-032) carry support_rank '-' — no rank by
    # construction; the top-N subset only exists for credited zones.
    ranked = {zid: meta[zid]['support_rank'] for zid in labels
              if isinstance(meta[zid]['support_rank'], int)}
    topn_rows = [labels[zid] for zid, rank in ranked.items()
                 if rank <= args.n_zones]

    # The provenance paragraph names the actual inputs of the mode, so a
    # reader reproducing the census cannot be sent to the credited round's
    # files by the table's own header.
    if ranked:
        lines = [
            '# Hand classification of the support-credited B zones '
            '(TOPO-029)',
            '',
            '_Generated by `summarize_zones_b.py` from `zone_labels_b.csv`;',
            'the class criteria were declared in `ZONE_CRITERIA_B.md` before',
            'labelling; the cards are in',
            '`output/topo/real_paris4/zones_png_b/` (`render_zones_b.py`).',
            'The summary sentence at the bottom comes from the same code as',
            'the table._',
            '',
        ]
    else:
        lines = [
            '# Census of the uncredited B zones (TOPO-032)',
            '',
            '_Generated by `summarize_zones_b.py` from',
            '`zone_labels_census_b.csv`; the class criteria were declared in',
            '`ZONE_CRITERIA_B.md` before labelling; the cards are in',
            '`output/topo/real_paris4/zones_png_census_b/`',
            '(`render_zones_b.py`). The summary sentence at the bottom comes',
            'from the same code as the table._',
            '',
        ]
    sections = [(f'All credited zones (top {4 * args.n_zones} of the '
                 'ranking)' if ranked else
                 'All uncredited zones (the TOPO-032 census)', all_rows)]
    if topn_rows:
        sections.append(
            (f'Top-N subset (rank ≤ {args.n_zones}, recall@N)',
             topn_rows))
    for title, rows in sections:
        n, counts, low = shares(rows)
        lines += [f'## {title} — {n} zones', '',
                  '| class | zones | share | of them confidence=low |',
                  '|---|---|---|---|']
        for c in CLASSES:
            lines.append(f'| {EN[c]} (`{c}`) | {counts[c]} | '
                         f'{counts[c] / n:.1%} | {low[c]} |')
        lines.append('')

    lines += ['## Zone table', '',
              '| id | segment | rows | cols | mass | rank | class | '
              'conf | note |',
              '|---|---|---|---|---|---|---|---|---|']
    for zid in sorted(labels):
        z, r = meta[zid], labels[zid]
        lines.append(
            f"| {zid} | {z['segment'].split('-w')[1]} | "
            f"{z['row_lo']}–{z['row_hi']} | {z['col_lo']}–{z['col_hi']} | "
            f"{z['mass']} | {z['support_rank']} | `{r['class']}` | "
            f"{r['confidence']} | {note_of(r)} |")

    n, counts, low = shares(all_rows)
    kind = ('support-credited' if ranked else 'uncredited')
    sentence = (
        f'In one line: of the {n} {kind} zones of corpus B, '
        f'genuine tracing errors — **{counts["real_error"]}** '
        f'({counts["real_error"] / n:.0%}; {low["real_error"]} of them '
        f'at low confidence), edges of the reference sector — '
        f'{counts["banner_edge"]} ({counts["banner_edge"] / n:.0%}), '
        f'epoch-fitting systematics — {counts["epoch_drift"]} '
        f'({counts["epoch_drift"] / n:.0%}), false alarms — '
        f'{counts["false_alarm"]} ({counts["false_alarm"] / n:.0%}).')
    lines += ['', sentence, '']

    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(sentence)


if __name__ == '__main__':
    main()
