"""Table and summary of the 124-zone manual classification (TOPO-020).

Reads `zone_labels.csv` (id, class, confidence, note — labelled by eye
against the criteria of `ZONE_CRITERIA.md`, declared before labelling) and
`zones_png/zones_meta.json` (provenance of every zone), refuses to run on an
incomplete labelling, and writes `ZONES_124.md`: per-class shares, the full
table, and the summary sentence — generated by the same code as the table
(PROTOCOL §8; the wave-2 stale-sentence lesson).

Usage:
    python oneshot/real_errors/summarize_zones.py \
        --labels oneshot/real_errors/zone_labels.csv \
        --meta output/topo/real_paris4/zones_png/zones_meta.json \
        --out oneshot/real_errors/ZONES_124.md
"""

import argparse
import csv
import json

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

CLASSES = ('real_error', 'tolerated_overlap', 'model_artifact', 'false_alarm')
EN = {'real_error': 'genuine switch/merger',
      'tolerated_overlap': 'tolerated annotation overlap',
      'model_artifact': 'model-disagreement artifact',
      'false_alarm': 'detector false alarm'}


def note_of(row):
    """The English reading of a by-eye note.

    `note` is the observation as the labeller wrote it at labelling time and
    is never rewritten; `note_en` is its English rendering, added later as a
    separate column. Tables render `note_en` only — a missing rendering stops
    the run, so the shipped English table cannot silently pick up a Russian
    cell from a half-labelled round.
    """
    text = (row.get('note_en') or '').strip()
    if not text:
        raise SystemExit(f"note_en missing for zone {row['id']} — every row "
                         f"needs an English note before the table is written")
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--labels', required=True)
    parser.add_argument('--meta', required=True)
    parser.add_argument('--out', required=True)
    args = parser.parse_args()

    with open(args.meta, encoding='utf-8') as f:
        meta = json.load(f)
    # utf-8-sig, matching the sibling scripts: these CSVs pass through
    # BOM-writing editors (one shipped file arrived with a BOM), and a BOM
    # under plain utf-8 turns the first field name into '﻿id'.
    with open(args.labels, encoding='utf-8-sig', newline='') as f:
        labels = {row['id']: row for row in csv.DictReader(f)}

    missing = sorted(set(meta) - set(labels))
    extra = sorted(set(labels) - set(meta))
    if missing or extra:
        raise SystemExit(f'labelling incomplete: missing {missing[:5]}... '
                         f'({len(missing)}), extra {extra}')
    bad = {i: r['class'] for i, r in labels.items()
           if r['class'] not in CLASSES}
    if bad:
        raise SystemExit(f'unknown classes: {bad}')

    n = len(labels)
    counts = {c: sum(1 for r in labels.values() if r['class'] == c)
              for c in CLASSES}
    low = {c: sum(1 for r in labels.values()
                  if r['class'] == c and r['confidence'] == 'low')
           for c in CLASSES}

    lines = [
        '# Hand classification of the 124 double-evidence zones (TOPO-020)',
        '',
        '_Generated by `summarize_zones.py` from `zone_labels.csv`; the class',
        'criteria were declared in `ZONE_CRITERIA.md` before labelling; the',
        'zone cards are in `output/topo/real_paris4/zones_png/`',
        '(`render_zones.py`). The summary sentence at the bottom comes from',
        'the same code as the table._',
        '',
        '## Shares by class',
        '',
        '| class | zones | share | of them confidence=low |',
        '|---|---|---|---|',
    ]
    for c in CLASSES:
        lines.append(f'| {EN[c]} (`{c}`) | {counts[c]} | '
                     f'{counts[c] / n:.1%} | {low[c]} |')
    lines += ['', '## Zone table', '',
              '| id | segment | rows | cols | mass | recto-only | '
              'rank | class | conf | note |',
              '|---|---|---|---|---|---|---|---|---|---|']
    for zid in sorted(labels):
        z, r = meta[zid], labels[zid]
        lines.append(
            f"| {zid} | {z['segment'].split('-w')[1]} | "
            f"{z['row_lo']}–{z['row_hi']} | {z['col_lo']}–{z['col_hi']} | "
            f"{z['mass']} | {z['recto_only'] / max(z['mass'], 1):.0%} | "
            f"{z['detector_rank']} | `{r['class']}` | {r['confidence']} | "
            f"{note_of(r)} |")

    real = counts['real_error']
    real_low = low['real_error']
    sentence = (
        f'In one line: of the {n} double-evidence zones, genuine errors '
        f'(switch/merger) — **{real}** '
        f'({real / n:.0%}; {real_low} of them at low confidence), '
        f'tolerated annotation overlaps — {counts["tolerated_overlap"]} '
        f'({counts["tolerated_overlap"] / n:.0%}), model-disagreement '
        f'artifacts — {counts["model_artifact"]} '
        f'({counts["model_artifact"] / n:.0%}), detector false alarms — '
        f'{counts["false_alarm"]} ({counts["false_alarm"] / n:.0%}).')
    lines += ['', sentence, '']

    with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(sentence)


if __name__ == '__main__':
    main()
