"""The v5 ablation's table, deltas and ship-rule verdicts, from the report alone.

Same disciplines as ablation_summary_v4.py: shared bootstrap resamples across
configurations, paired per-resample differences with their own percentile
intervals, and verdicts generated from the same dicts as the table. The ship
rule is v3/v4's, restated in detect_v5.py §6: a learned form is a held-out
candidate only if, against v1, AP or M improves significantly AND none of
AP / recall@N / S / M / H / plausible degrades significantly. This file marks
every learned form against that rule; which single form (if any) goes to
held-out is then fixed in ABLATION_V5.md by hand, before any held-out run.

Usage (from oneshot/detector/):

    python ablation_summary_v5.py --report ../../output/topo/detector_v5_paris4.json \
        --out ABLATION_V5.md
"""
import argparse
import json

import numpy as np

from ablation_summary import config_terms
from heldout_summary import load_injection_info

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815

KEYS = ('ap', 'recall', 'S', 'M', 'H', 'plausible')
LEARNED = ('v5l (logit, v1 pool)', 'v5lu (logit, union)',
           'v5b (boosting, v1 pool)', 'v5bu (boosting, union)')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(args.report, encoding='utf-8') as f:
        report = json.load(f)
    info = load_injection_info(report) or {}

    configs = {
        'v1 (percentile)': report['ablation_v1_config'],
        'v3u (percentile)': report['ablation_v3u_config'],
        'v3uq (quotas)': report['ablation_v3uq_config'],
        'v5l (logit, v1 pool)': report['ablation_v5l_config'],
        'v5lu (logit, union)': {
            key: report[key] for key in
            ('metrics', 'recall_by_type', 'recall_by_band',
             'recall_on_locally_plausible', 'per_rank_outcomes',
             'per_injection_rank')},
        'v5b (boosting, v1 pool)': report['ablation_v5b_config'],
        'v5bu (boosting, union)': report['ablation_v5bu_config'],
    }
    ids = sorted(report['per_injection_rank'])
    n = len(ids)
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))

    members = {}
    for label, select in (
            ('S', lambda i: info.get(i, (None,))[0] == 'S'),
            ('M', lambda i: info.get(i, (None,))[0] == 'M'),
            ('H', lambda i: info.get(i, (None,))[0] == 'H'),
            ('plausible', lambda i: bool(info.get(i, (None, False))[1]))):
        members[label] = np.array([1.0 if select(i) else 0.0 for i in ids])

    def ci(values):
        return (float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    resampled = {}
    for label, block in configs.items():
        ap_terms, recall_terms = config_terms(block, ids)
        entry = {'ap': ap_terms[samples].mean(axis=1),
                 'recall': recall_terms[samples].mean(axis=1)}
        for sub, member in members.items():
            hits = (recall_terms * member)[samples].sum(axis=1)
            sizes = member[samples].sum(axis=1)
            ok = sizes > 0
            entry[sub] = hits[ok] / sizes[ok]
        resampled[label] = entry

    hp = report.get('hyperparameters', {})
    lines = ['# Ablation v5 (TOPO-035, learned fusion) — generated by ablation_summary_v5.py',
             '',
             '',
             f'_Dev corpus, N={n}; 95 % bootstrap intervals over injections '
             f'({BOOTSTRAP_RESAMPLES} resamples, seed {BOOTSTRAP_SEED}), '
             'shared across all configurations; the Δ rows are paired '
             'differences on the same resamples (significant if the interval excludes 0). '
             'Protocol — the detect_v5.py header, declared before training: '
             '7 features (family, per-family log1p(mass), a vertical-jump '
             'factor), leave-one-segment-out splits, '
             f'logit (λ={hp.get("logit", {}).get("l2")}), stump boosting '
             f'({hp.get("boost", {}).get("rounds")} rounds, '
             f'lr {hp.get("boost", {}).get("lr")})._',
             '',
             '| configuration | AP | recall@N | S | M | H | plausible |',
             '|---|---|---|---|---|---|---|']

    def cell(block, key, resampled_key, digits=3):
        if key == 'ap':
            point = block['metrics']['ap']
            digits = 4
        elif key == 'recall':
            point = block['metrics']['recall_at_n']
        elif key == 'plausible':
            point = block['recall_on_locally_plausible']
        else:
            point = block['recall_by_type'].get(key)
        if point is None:
            return 'n/a'
        lo, hi = ci(resampled[resampled_key][key if key != 'recall'
                                             else 'recall'])
        return f'{point:.{digits}f} [{lo:.2f}–{hi:.2f}]'

    for label, block in configs.items():
        cells = [cell(block, key, label) for key in KEYS]
        lines.append(f'| {label} | ' + ' | '.join(cells) + ' |')

    def delta_row(label_a, label_b, caption):
        cells = []
        for key in KEYS:
            a, b = resampled[label_a][key], resampled[label_b][key]
            m = min(len(a), len(b))
            delta = a[:m] - b[:m]
            lo, hi = ci(delta)
            point = float(np.mean(delta))
            mark = ' **significant**' if lo > 0 or hi < 0 else ''
            cells.append(f'{point:+.3f} [{lo:+.2f}–{hi:+.2f}]{mark}')
        lines.append(f'| {caption} | ' + ' | '.join(cells) + ' |')

    base = 'v1 (percentile)'
    for label in LEARNED:
        delta_row(label, base, f'Δ {label} − v1')
    delta_row('v5lu (logit, union)', 'v3u (percentile)', 'Δ v5lu − v3u')
    delta_row('v5lu (logit, union)', 'v3uq (quotas)', 'Δ v5lu − v3uq')

    def paired(label_a, label_b, key):
        a, b = resampled[label_a][key], resampled[label_b][key]
        m = min(len(a), len(b))
        lo, hi = ci(a[:m] - b[:m])
        return float(np.mean(a[:m] - b[:m])), lo, hi

    lines += ['', '## The shipping rule against v1 (per form, in detail)', '']
    for label in LEARNED:
        gains, losses = [], []
        for key in KEYS:
            point, lo, hi = paired(label, base, key)
            if lo > 0:
                gains.append(key)
            if hi < 0:
                losses.append((key, point, lo, hi))
        ap = paired(label, base, 'ap')
        passes = (('ap' in gains or 'M' in gains) and not losses)
        loss_text = ('; '.join(f'Δ{k} {p:+.3f} [{lo:+.2f}–{hi:+.2f}]'
                               for k, p, lo, hi in losses)
                     if losses else 'no significant losses')
        lines.append(
            f'- **{label}**: ΔAP {ap[0]:+.4f} [{ap[1]:+.2f}–{ap[2]:+.2f}]; '
            f'significant gains: {", ".join(gains) if gains else "none"}; '
            f'{loss_text} — the shipping rule is '
            + ('**PASSED**.' if passes else 'not met.'))
    lines.append('')

    text = '\n'.join(lines)
    print(text)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
