"""The v3 ablation's table and its summary sentence, from the report alone.

Same disciplines as ablation_summary.py (TOPO-023), applied to the CT channel
(TOPO-026): shared bootstrap resamples across configurations, paired
per-resample differences with their own percentile intervals, and a summary
sentence generated from the same dicts as the table.

Usage (from oneshot/detector/):

    python ablation_summary_v3.py --report ../../output/topo/detector_v3_paris4.json \
        --out ABLATION_V3.md
"""
import argparse
import json

import numpy as np

from ablation_summary import config_terms
from heldout_summary import load_injection_info

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(args.report, encoding='utf-8') as f:
        report = json.load(f)
    info = load_injection_info(report) or {}

    configs = {
        'v1 (prox+rect+support)': report['ablation_v1_config'],
        'v3 (ct replaces support)': {
            key: report[key] for key in
            ('metrics', 'recall_by_type', 'recall_by_band',
             'recall_on_locally_plausible', 'per_rank_outcomes',
             'per_injection_rank')},
        'v3add (v1 + ct)': report['ablation_v3add_config'],
        'v3u (ct merged into support)': report['ablation_v3u_config'],
        'v3w (ct corroboration weight only)': report['ablation_v3w_config'],
    }
    ids = sorted(report['per_injection_rank'])
    n = len(ids)
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))

    members = {}
    for label, select in (
            ('S', lambda i: info.get(i, (None,))[0] == 'S'),
            ('M', lambda i: info.get(i, (None,))[0] == 'M'),
            ('H', lambda i: info.get(i, (None,))[0] == 'H'),
            ('plausible', lambda i: bool(info.get(i, (None, False))[1]))):
        members[label] = np.array([1.0 if select(i) else 0.0 for i in ids])

    def ci(values):
        return (float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    resampled = {}
    for label, block in configs.items():
        ap_terms, recall_terms = config_terms(block, ids)
        entry = {'ap': ap_terms[samples].mean(axis=1),
                 'recall': recall_terms[samples].mean(axis=1)}
        for sub, member in members.items():
            hits = (recall_terms * member)[samples].sum(axis=1)
            sizes = member[samples].sum(axis=1)
            ok = sizes > 0
            entry[sub] = hits[ok] / sizes[ok]
        resampled[label] = entry

    lines = ['# Ablation v3 (TOPO-026, the CT channel) — generated by ablation_summary_v3.py',
             '',
             '',
             f'_Dev corpus, N={n}; 95 % bootstrap intervals over injections '
             f'({BOOTSTRAP_RESAMPLES} resamples, seed {BOOTSTRAP_SEED}), '
             'shared across all configurations; the Δ rows are paired '
             'differences on the same resamples (significant if the interval excludes 0)._',
             '',
             '| configuration | AP | recall@N | S | M | H | plausible |',
             '|---|---|---|---|---|---|---|']

    def cell(block, key, resampled_key, digits=3):
        if key == 'ap':
            point = block['metrics']['ap']
            digits = 4
        elif key == 'recall':
            point = block['metrics']['recall_at_n']
        elif key == 'plausible':
            point = block['recall_on_locally_plausible']
        else:
            point = block['recall_by_type'].get(key)
        if point is None:
            return 'n/a'
        lo, hi = ci(resampled[resampled_key][key if key != 'recall'
                                             else 'recall'])
        return f'{point:.{digits}f} [{lo:.2f}–{hi:.2f}]'

    for label, block in configs.items():
        cells = [cell(block, key, label)
                 for key in ('ap', 'recall', 'S', 'M', 'H', 'plausible')]
        lines.append(f'| {label} | ' + ' | '.join(cells) + ' |')

    base = 'v1 (prox+rect+support)'
    for label in configs:
        if label == base:
            continue
        cells = []
        for key in ('ap', 'recall', 'S', 'M', 'H', 'plausible'):
            a, b = resampled[label][key], resampled[base][key]
            m = min(len(a), len(b))
            delta = a[:m] - b[:m]
            lo, hi = ci(delta)
            point = float(np.mean(delta))
            mark = ' **significant**' if lo > 0 or hi < 0 else ''
            cells.append(f'{point:+.3f} [{lo:+.2f}–{hi:+.2f}]{mark}')
        lines.append(f'| Δ {label} − v1 | ' + ' | '.join(cells) + ' |')

    ct = report.get('ct_channel', {})
    cov = ct.get('probe_coverage', {})
    lines += ['',
              f"Mechanism: the CT channel produced {ct.get('candidates')} candidates at "
              f"T={ct.get('threshold')}; probe coverage of the windows: "
              f"M missed by v1 {cov.get('M_missed_by_v1', {}).get('covered')}"
              f"/{cov.get('M_missed_by_v1', {}).get('n')}, "
              f"H {cov.get('H_all', {}).get('covered')}"
              f"/{cov.get('H_all', {}).get('n')}.",
              '']

    deltas = {}
    for key in ('ap', 'M', 'S'):
        a = resampled['v3 (ct replaces support)'][key]
        b = resampled[base][key]
        m = min(len(a), len(b))
        lo, hi = ci(a[:m] - b[:m])
        deltas[key] = (float(np.mean(a[:m] - b[:m])), lo, hi)
    verdict = ('significant' if deltas['M'][1] > 0
               else 'significantly negative' if deltas['M'][2] < 0
               else 'within noise')
    sentence = (f"In one line: replacing support→ct gives ΔM "
                f"{deltas['M'][0]:+.3f} [{deltas['M'][1]:+.2f}–"
                f"{deltas['M'][2]:+.2f}], ΔS {deltas['S'][0]:+.3f} "
                f"[{deltas['S'][1]:+.2f}–{deltas['S'][2]:+.2f}] and ΔAP "
                f"{deltas['ap'][0]:+.4f} [{deltas['ap'][1]:+.2f}–"
                f"{deltas['ap'][2]:+.2f}] — the merger effect is {verdict}.")
    lines += [sentence, '']

    text = '\n'.join(lines)
    print(text)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
