"""TOPO-037 V8: the learned fusion on a FRESH SEED (corpus_paris4_v2).

Declared 17.08.2026, committed while the fresh-seed candidate generation was
still running — i.e. before any v2 candidate or label was seen:

- Pool: replayed from the ckpt_paris4v2_dev checkpoints written by the
  detect_v1 run on corpus_paris4_v2 (seed 20260817, dev bands, prediction
  channel on); checkpoint key is verified, mismatched keys abort.
- v1 anchor: the frozen percentile merge on the same fresh pool (this IS the
  fresh seed's v1 — there is no older report to regress against; its AP is
  reported next to the dev-corpus 0.6442 as seed-stability context).
- Model: detect_v5's logit, lambda 1.0, LOSO over the v2 dev segments,
  labels from the v2 manifest by the same grown-rectangle rule. No constant
  differs from the declared v5 protocol.
- **Criterion (V8 passes iff):** paired-bootstrap AP delta of LOSO-v5l over
  the fresh-seed v1 is significantly positive (2000 resamples, seed
  20260815) AND no family recall degrades significantly — the ship rule's
  degradation clause, applied to the new seed.

Usage (from oneshot/detector/):

    python verify_v8.py --corpus ../../output/topo/corpus_paris4_v2 \
        --checkpoints ../../output/topo/ckpt_paris4v2_dev \
        --report ../../output/topo/verify_v8_report.json --out VERIFY_V8.md
"""
import argparse
import json
import os
import pickle
import sys

import numpy as np

# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, '..', '..', 'wave2', 'figures'))
sys.path.insert(0, os.path.join(_HERE, '..', 'metric'))
sys.path.insert(0, os.path.join(_HERE, '..'))
import sheet_erl                                                      # noqa: E402
import detect_v1 as v1                                                # noqa: E402
import detect_v5 as v5                                                # noqa: E402

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815
KEYS = ('ap', 'S', 'M', 'H')


def outcomes_of(rank, injections):
    return sheet_erl.hits(rank, injections, {})


def terms(outcomes, injections):
    n = len(injections)
    contrib, recall = np.zeros(n), np.zeros(n)
    tp = 0
    for i, (hit, *_rest) in enumerate(outcomes, 1):
        if hit is not None:
            tp += 1
            contrib[hit] = tp / i
            if i <= n:
                recall[hit] = 1.0
    return contrib, recall


def render_md(report):
    """VERIFY_V8.md purely from the report — no recomputation, no network.

    Split out of main() by TOPO-060 so verify.py can regenerate the shipped
    file offline and diff it; main() renders through this same function.
    Delta order is the declared one ('ap' then the families), not the
    report's key order.
    """
    deltas = report['paired_deltas']
    order = [k for k in ('ap', 'S', 'M', 'H') if k in deltas] + \
            [k for k in deltas if k not in ('ap', 'S', 'M', 'H')]
    return [
        '# V8 — fresh seed (TOPO-037) — generated by verify_v8.py', '',
        '',
        f"_Corpus corpus_paris4_v2 (seed {report['seed']}), "
        f"{report['n_injections']} "
        f"dev injections, pool {report['pool']}; the criterion was declared in the script "
        'header before any candidate existed._', '',
        '| configuration | AP | recall@N |', '|---|---|---|',
        f"| v1 (percentile, fresh seed) | {report['v1_ap']:.4f} "
        f"| {report['v1_recall']:.3f} |",
        f"| v5l (LOSO, fresh seed) | {report['v5l_ap']:.4f} "
        f"| {report['v5l_recall']:.3f} |", '',
        'Paired Δ (v5l − v1): ' + ', '.join(
            f'{k} {deltas[k][0]:+.4f} [{deltas[k][1]:+.4f}..'
            f'{deltas[k][2]:+.4f}]'
            for k in order) + '.', '',
        '**Verdict: ' + ('PASSED' if report['passed'] else 'NOT PASSED')
        + '** by the declared criterion.', '']


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--corpus', required=True)
    parser.add_argument('--checkpoints', required=True)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(os.path.join(args.corpus, 'manifest.json'),
              encoding='utf-8') as f:
        manifest = json.load(f)
    injections = [r for r in manifest['injections'] if r['winding_low'] < 100]
    names = sorted({r['segment'] for r in injections})
    n = len(injections)

    key = {'corpus': os.path.abspath(args.corpus), 'bands': 'dev',
           'with_prediction': True}
    pool = []
    for name in names:
        path = os.path.join(args.checkpoints, f'{name}.pkl')
        with open(path, 'rb') as f:
            payload = pickle.load(f)
        if payload.get('key') != key:
            raise SystemExit(f'{path}: checkpoint key mismatch')
        pool += [tuple(c) for c in payload['candidates']]
    print(f'fresh-seed pool: {len(pool)} candidates, '
          f'{n} injections, {len(names)} segments')

    rank_v1 = v1.merge_channels(pool, top=4 * n)
    out_v1 = outcomes_of(rank_v1, injections)
    ap_v1 = sheet_erl.average_precision(out_v1, n)

    X = v5.feature_matrix(pool)
    y = v5.label_vector(pool, injections)
    scores = np.zeros(len(pool))
    for seg in names:
        test = np.array([c[0] == seg for c in pool])
        model = v5.fit_logit(X[~test], y[~test])
        scores[test] = v5.predict_logit(model, X[test])
    rank_v5 = v5.ranking_from_scores(pool, scores, top=4 * n)
    out_v5 = outcomes_of(rank_v5, injections)
    ap_v5 = sheet_erl.average_precision(out_v5, n)

    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))
    c5, r5 = terms(out_v5, injections)
    c1, r1 = terms(out_v1, injections)

    def ci(values):
        return (float(np.mean(values)), float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    deltas = {'ap': ci((c5 - c1)[samples].mean(axis=1))}
    for t in 'SMH':
        member = np.array([1.0 if r['type'] == t else 0.0
                           for r in injections])
        num = ((r5 - r1) * member)[samples].sum(axis=1)
        den = member[samples].sum(axis=1)
        ok = den > 0
        deltas[t] = ci(num[ok] / den[ok])

    sig_loss = [k for k in KEYS if deltas[k][2] < 0]
    passed = bool(deltas['ap'][1] > 0 and not sig_loss)
    recall_v5 = sum(1 for h, *_ in out_v5[:n] if h is not None) / n
    recall_v1 = sum(1 for h, *_ in out_v1[:n] if h is not None) / n

    report = {'seed': manifest.get('seed'), 'n_injections': n,
              'pool': len(pool), 'v1_ap': ap_v1, 'v5l_ap': ap_v5,
              'v1_recall': recall_v1, 'v5l_recall': recall_v5,
              'paired_deltas': {k: list(v) for k, v in deltas.items()},
              'significant_losses': sig_loss,
              'criterion': 'delta AP significantly > 0 AND no family '
                           'recall degrades significantly',
              'passed': passed}
    with open(args.report, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(report, f, ensure_ascii=False, indent=1, sort_keys=True)

    print(f'fresh-seed v1: AP {ap_v1:.4f}, recall {recall_v1:.3f}')
    print(f'fresh-seed v5l (LOSO): AP {ap_v5:.4f}, recall {recall_v5:.3f}')
    print('deltas: ' + ', '.join(
        f'{k} {v[0]:+.4f} [{v[1]:+.4f}..{v[2]:+.4f}]'
        for k, v in deltas.items()))
    print('V8 -> ' + ('PASS' if passed
                      else f'FAIL (losses: {sig_loss or "no sig AP gain"})'))

    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write('\n'.join(render_md(report)))
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
