"""The v2 ablation's table and its summary sentence, from the report alone.

TOPO-023's deliverable is a dev-corpus comparison of the frozen v1 against the
front-channel configurations, with intervals. Two disciplines carry over from
heldout_summary.py: the summary sentence comes out of the same dicts as the
table (the stale-summary lesson), and every number has its uncertainty
printed beside it. One discipline is new here: the configurations are
compared on *shared* bootstrap resamples, so the interesting quantity — the
per-resample difference (config minus v1) — gets its own percentile interval.
Two overlapping marginal intervals can hide a consistently-signed paired
difference; the paired interval is the honest test of "did the front channel
move the metric".

Usage (from pipeline/detector/):

    python ablation_summary.py --report ../../output/topo/detector_v2_paris4.json \
        --out ABLATION_V2.md
"""
import argparse
import json
import os

import numpy as np

from heldout_summary import load_injection_info

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815


def config_terms(block, ids):
    """Per-injection AP contributions and recall indicators of one config."""
    contribution = {injection: 0.0 for injection in ids}
    tp = 0
    for i, credited in enumerate(block['per_rank_outcomes'], 1):
        if credited is not None:
            tp += 1
            contribution[credited] = tp / i
    ranks = block['per_injection_rank']
    ap = np.array([contribution[i] for i in ids])
    recall = np.array([1.0 if ranks[i] is not None and ranks[i] <= len(ids)
                       else 0.0 for i in ids])
    return ap, recall


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(args.report, encoding='utf-8') as f:
        report = json.load(f)
    info = load_injection_info(report) or {}

    configs = {
        'v1 (prox+rect+support)': report['ablation_v1_config'],
        'v2 (front replaces support)': {
            key: report[key] for key in
            ('metrics', 'recall_by_type', 'recall_by_band',
             'recall_on_locally_plausible', 'per_rank_outcomes',
             'per_injection_rank')},
        'v2add (all four)': report['ablation_v2add_config'],
    }
    ids = sorted(report['per_injection_rank'])
    n = len(ids)
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))

    members = {}
    for label, select in (
            ('S', lambda i: info.get(i, (None,))[0] == 'S'),
            ('M', lambda i: info.get(i, (None,))[0] == 'M'),
            ('H', lambda i: info.get(i, (None,))[0] == 'H'),
            ('plausible', lambda i: bool(info.get(i, (None, False))[1]))):
        members[label] = np.array([1.0 if select(i) else 0.0 for i in ids])

    def ci(values):
        return (float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    resampled = {}
    for label, block in configs.items():
        ap_terms, recall_terms = config_terms(block, ids)
        entry = {'ap': ap_terms[samples].mean(axis=1),
                 'recall': recall_terms[samples].mean(axis=1)}
        for sub, member in members.items():
            hits = (recall_terms * member)[samples].sum(axis=1)
            sizes = member[samples].sum(axis=1)
            ok = sizes > 0
            entry[sub] = hits[ok] / sizes[ok]
        resampled[label] = entry

    lines = ['# Ablation v2 (TOPO-023) — generated by ablation_summary.py',
             '',
             '',
             f'_Dev corpus, N={n}; 95 % bootstrap intervals over injections '
             f'({BOOTSTRAP_RESAMPLES} resamples, seed {BOOTSTRAP_SEED}), '
             'shared across all configurations; the Δ rows are paired '
             'differences on the same resamples (significant if the interval excludes 0)._',
             '',
             '| configuration | AP | recall@N | S | M | H | plausible |',
             '|---|---|---|---|---|---|---|']

    def cell(block, key, resampled_key, digits=3):
        if key == 'ap':
            point = block['metrics']['ap']
            digits = 4
        elif key == 'recall':
            point = block['metrics']['recall_at_n']
        elif key == 'plausible':
            point = block['recall_on_locally_plausible']
        else:
            point = block['recall_by_type'].get(key)
        if point is None:
            return 'n/a'
        lo, hi = ci(resampled[resampled_key][key if key != 'recall'
                                             else 'recall'])
        return f'{point:.{digits}f} [{lo:.2f}–{hi:.2f}]'

    for label, block in configs.items():
        cells = [cell(block, key, label)
                 for key in ('ap', 'recall', 'S', 'M', 'H', 'plausible')]
        lines.append(f'| {label} | ' + ' | '.join(cells) + ' |')

    base = 'v1 (prox+rect+support)'
    for label in configs:
        if label == base:
            continue
        cells = []
        for key in ('ap', 'recall', 'S', 'M', 'H', 'plausible'):
            a, b = resampled[label][key], resampled[base][key]
            m = min(len(a), len(b))
            delta = a[:m] - b[:m]
            lo, hi = ci(delta)
            point = float(np.mean(delta))
            mark = ' **significant**' if lo > 0 or hi < 0 else ''
            cells.append(f'{point:+.3f} [{lo:+.2f}–{hi:+.2f}]{mark}')
        lines.append(f'| Δ {label} − v1 | ' + ' | '.join(cells) + ' |')

    probe = report.get('front_probe', {})
    lines += ['',
              f"Mechanism: the front channel produced {probe.get('candidates')} "
              f"candidates; share of injection windows carrying front evidence, "
              f"by type: {probe.get('per_type_window_hits')}.",
              '']

    deltas = {}
    for key in ('ap', 'M'):
        a = resampled['v2 (front replaces support)'][key]
        b = resampled[base][key]
        m = min(len(a), len(b))
        lo, hi = ci(a[:m] - b[:m])
        deltas[key] = (float(np.mean(a[:m] - b[:m])), lo, hi)
    verdict = ('significant' if deltas['M'][1] > 0
               else 'significantly negative' if deltas['M'][2] < 0
               else 'within noise')
    sentence = (f"In one line: replacing support→front gives ΔM "
                f"{deltas['M'][0]:+.3f} [{deltas['M'][1]:+.2f}–"
                f"{deltas['M'][2]:+.2f}] and ΔAP {deltas['ap'][0]:+.4f} "
                f"[{deltas['ap'][1]:+.2f}–{deltas['ap'][2]:+.2f}] — "
                f"the merger effect is {verdict}.")
    lines += [sentence, '']

    text = '\n'.join(lines)
    print(text)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
