"""The v7 (TOPO-040, pair features) table, deltas and ship-rule verdict.

Same disciplines as ablation_summary_v5/v6: shared bootstrap resamples,
paired per-resample differences with their own percentile intervals,
verdict generated from the same dicts as the table. The ship rule is
detect_v7.py §5 (= detect_v6.py §7) against the replayed v5lu; the task's
target column is S (the 9 below-N switches), read with the same discipline.

Usage (from pipeline/detector/):

    python ablation_summary_v7.py \
        --report ../../output/topo/detector_v7_paris4.json [--out FILE]
"""
import argparse
import json

import numpy as np

from ablation_summary import config_terms
from heldout_summary import load_injection_info

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815

KEYS = ('ap', 'recall', 'S', 'M', 'H', 'plausible')
V7 = 'v7l (pair features on top of v5lu)'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(args.report, encoding='utf-8') as f:
        report = json.load(f)
    info = load_injection_info(report) or {}

    configs = {
        'v5lu (replay, comparison point)': report['ablation_v5lu_config'],
        V7: {key: report[key] for key in
             ('metrics', 'recall_by_type', 'recall_on_locally_plausible',
              'per_rank_outcomes', 'per_injection_rank')},
    }
    ids = sorted(report['per_injection_rank'])
    n = len(ids)
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))

    members = {}
    for label, select in (
            ('S', lambda i: info.get(i, (None,))[0] == 'S'),
            ('M', lambda i: info.get(i, (None,))[0] == 'M'),
            ('H', lambda i: info.get(i, (None,))[0] == 'H'),
            ('plausible', lambda i: bool(info.get(i, (None, False))[1]))):
        members[label] = np.array([1.0 if select(i) else 0.0 for i in ids])

    def ci(values):
        return (float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    resampled = {}
    for label, block in configs.items():
        ap_terms, recall_terms = config_terms(block, ids)
        entry = {'ap': ap_terms[samples].mean(axis=1),
                 'recall': recall_terms[samples].mean(axis=1)}
        for sub, member in members.items():
            hits = (recall_terms * member)[samples].sum(axis=1)
            sizes = member[samples].sum(axis=1)
            ok = sizes > 0
            entry[sub] = hits[ok] / sizes[ok]
        resampled[label] = entry

    rule = report.get('pair_rule', {})
    stats = report.get('pair_stats', {})
    lines = ['# Ablation v7 (TOPO-040, the through-winding pair) — '
             'generated by ablation_summary_v7.py',
             '',
             '',
             f'_Dev corpus, N={n}; 95 % bootstrap intervals over injections '
             f'({BOOTSTRAP_RESAMPLES} resamples, seed {BOOTSTRAP_SEED}), '
             'shared across configurations; the Δ row is paired differences on the same '
             'resamples (significant if the interval excludes 0). Protocol — '
             'the detect_v7.py header, declared before the run: pair rule '
             f'{rule}; pair statistics {stats}._',
             '',
             '| configuration | AP | recall@N | S | M | H | plausible |',
             '|---|---|---|---|---|---|---|']

    def cell(block, key, resampled_key, digits=3):
        if key == 'ap':
            point = block['metrics']['ap']
            digits = 4
        elif key == 'recall':
            point = block['metrics']['recall_at_n']
        elif key == 'plausible':
            point = block['recall_on_locally_plausible']
        else:
            point = block['recall_by_type'].get(key)
        if point is None:
            return 'n/a'
        lo, hi = ci(resampled[resampled_key][key if key != 'recall'
                                             else 'recall'])
        return f'{point:.{digits}f} [{lo:.2f}–{hi:.2f}]'

    for label, block in configs.items():
        cells = [cell(block, key, label) for key in KEYS]
        lines.append(f'| {label} | ' + ' | '.join(cells) + ' |')

    base = 'v5lu (replay, comparison point)'

    def paired(key):
        a, b = resampled[V7][key], resampled[base][key]
        m = min(len(a), len(b))
        lo, hi = ci(a[:m] - b[:m])
        return float(np.mean(a[:m] - b[:m])), lo, hi

    cells = []
    for key in KEYS:
        point, lo, hi = paired(key)
        mark = ' **significant**' if lo > 0 or hi < 0 else ''
        cells.append(f'{point:+.3f} [{lo:+.2f}–{hi:+.2f}]{mark}')
    lines.append('| Δ v7l − v5lu | ' + ' | '.join(cells) + ' |')

    gains, losses = [], []
    for key in KEYS:
        point, lo, hi = paired(key)
        if lo > 0:
            gains.append(key)
        if hi < 0:
            losses.append((key, point, lo, hi))
    ap = paired('ap')
    s = paired('S')
    passes = (('ap' in gains or 'M' in gains) and not losses)
    loss_text = ('; '.join(f'Δ{k} {p:+.3f} [{lo:+.2f}–{hi:+.2f}]'
                           for k, p, lo, hi in losses)
                 if losses else 'no significant losses')
    lines += ['', '## The shipping rule against v5lu (detect_v7.py §5)', '',
              f'- **{V7}**: ΔAP {ap[0]:+.4f} [{ap[1]:+.2f}–{ap[2]:+.2f}]; '
              f'ΔS {s[0]:+.3f} [{s[1]:+.2f}–{s[2]:+.2f}]; '
              f'significant gains: {", ".join(gains) if gains else "none"}; '
              f'{loss_text} — the shipping rule is '
              + ('**PASSED**.' if passes else 'not met.')]

    text = '\n'.join(lines) + '\n'
    print(text)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
