"""The v6 ablation's table, deltas and ship-rule verdicts, from the report alone.

Same disciplines as ablation_summary_v5.py: shared bootstrap resamples across
configurations, paired per-resample differences with their own percentile
intervals, verdicts generated from the same dicts as the table. The ship rule
is detect_v6.py §7: a form is a candidate for any future exam only if,
against the replayed v5lu, AP or M improves significantly AND none of
AP / recall@N / S / M / H / plausible degrades significantly. Only v6l and
v6b are shippable forms; v6l_novjump and v6l_thin are attribution rows
(detect_v6.py §6) and are marked accordingly.

Usage (from pipeline/detector/):

    python ablation_summary_v6.py --report ../../output/topo/detector_v6_paris4.json \
        --out ABLATION_V6.md
"""
import argparse
import json

import numpy as np

from ablation_summary import config_terms
from heldout_summary import load_injection_info

import sys
# A Windows console defaults to a legacy code page, and the records below carry
# Cyrillic, Delta and the minus sign. Substitute the unrepresentable rather than
# raise: the numbers are the payload, and a UnicodeEncodeError would hide all of
# them behind the first one that does not fit.
for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, 'reconfigure'):
        _stream.reconfigure(errors='replace')

BOOTSTRAP_RESAMPLES = 2000
BOOTSTRAP_SEED = 20260815

KEYS = ('ap', 'recall', 'S', 'M', 'H', 'plausible')
SHIPPABLE = ('v6l (logit, 14 features)', 'v6b (boosting, 14 features)')
ATTRIBUTION = ('v6l_novjump (without the vjump family)',
               'v6l_thin (11 features, no cluster ones)')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--report', required=True)
    parser.add_argument('--out', default=None)
    args = parser.parse_args()

    with open(args.report, encoding='utf-8') as f:
        report = json.load(f)
    info = load_injection_info(report) or {}

    configs = {
        'v5lu (replay, comparison point)': report['ablation_v5lu_config'],
        'v6l (logit, 14 features)': {
            key: report[key] for key in
            ('metrics', 'recall_by_type', 'recall_by_band',
             'recall_on_locally_plausible', 'per_rank_outcomes',
             'per_injection_rank')},
        'v6b (boosting, 14 features)': report['ablation_v6b_config'],
        'v6l_novjump (without the vjump family)':
            report['ablation_v6l_novjump_config'],
        'v6l_thin (11 features, no cluster ones)':
            report['ablation_v6l_thin_config'],
    }
    ids = sorted(report['per_injection_rank'])
    n = len(ids)
    rng = np.random.default_rng(BOOTSTRAP_SEED)
    samples = rng.integers(0, n, size=(BOOTSTRAP_RESAMPLES, n))

    members = {}
    for label, select in (
            ('S', lambda i: info.get(i, (None,))[0] == 'S'),
            ('M', lambda i: info.get(i, (None,))[0] == 'M'),
            ('H', lambda i: info.get(i, (None,))[0] == 'H'),
            ('plausible', lambda i: bool(info.get(i, (None, False))[1]))):
        members[label] = np.array([1.0 if select(i) else 0.0 for i in ids])

    def ci(values):
        return (float(np.percentile(values, 2.5)),
                float(np.percentile(values, 97.5)))

    resampled = {}
    for label, block in configs.items():
        ap_terms, recall_terms = config_terms(block, ids)
        entry = {'ap': ap_terms[samples].mean(axis=1),
                 'recall': recall_terms[samples].mean(axis=1)}
        for sub, member in members.items():
            hits = (recall_terms * member)[samples].sum(axis=1)
            sizes = member[samples].sum(axis=1)
            ok = sizes > 0
            entry[sub] = hits[ok] / sizes[ok]
        resampled[label] = entry

    floors = report.get('floors', {})
    cov = report.get('coverage', {})
    lines = ['# Ablation v6 (TOPO-038, the coverage iteration) — generated by ablation_summary_v6.py',
             '',
             '',
             f'_Dev corpus, N={n}; 95 % bootstrap intervals over injections '
             f'({BOOTSTRAP_RESAMPLES} resamples, seed {BOOTSTRAP_SEED}), '
             'shared across all configurations; the Δ rows are paired '
             'differences on the same resamples (significant if the interval excludes 0). '
             'Protocol — the detect_v6.py header, declared before the run: '
             f'floors {floors}; coverage ceiling of the v6 pool — '
             f"{cov.get('total')}/{cov.get('n')} against "
             f"{cov.get('v5_union_reference')}/{cov.get('n')} for the v5 union "
             f"(by family {cov.get('by_family')})._",
             '',
             '| configuration | AP | recall@N | S | M | H | plausible |',
             '|---|---|---|---|---|---|---|']

    def cell(block, key, resampled_key, digits=3):
        if key == 'ap':
            point = block['metrics']['ap']
            digits = 4
        elif key == 'recall':
            point = block['metrics']['recall_at_n']
        elif key == 'plausible':
            point = block['recall_on_locally_plausible']
        else:
            point = block['recall_by_type'].get(key)
        if point is None:
            return 'n/a'
        lo, hi = ci(resampled[resampled_key][key if key != 'recall'
                                             else 'recall'])
        return f'{point:.{digits}f} [{lo:.2f}–{hi:.2f}]'

    for label, block in configs.items():
        cells = [cell(block, key, label) for key in KEYS]
        lines.append(f'| {label} | ' + ' | '.join(cells) + ' |')

    base = 'v5lu (replay, comparison point)'

    def delta_row(label_a, caption):
        cells = []
        for key in KEYS:
            a, b = resampled[label_a][key], resampled[base][key]
            m = min(len(a), len(b))
            delta = a[:m] - b[:m]
            lo, hi = ci(delta)
            point = float(np.mean(delta))
            mark = ' **significant**' if lo > 0 or hi < 0 else ''
            cells.append(f'{point:+.3f} [{lo:+.2f}–{hi:+.2f}]{mark}')
        lines.append(f'| {caption} | ' + ' | '.join(cells) + ' |')

    for label in SHIPPABLE + ATTRIBUTION:
        delta_row(label, f'Δ {label.split(" ")[0]} − v5lu')

    def paired(label_a, key):
        a, b = resampled[label_a][key], resampled[base][key]
        m = min(len(a), len(b))
        lo, hi = ci(a[:m] - b[:m])
        return float(np.mean(a[:m] - b[:m])), lo, hi

    lines += ['', '## The shipping rule against v5lu (detect_v6.py §7)', '']
    for label in SHIPPABLE:
        gains, losses = [], []
        for key in KEYS:
            point, lo, hi = paired(label, key)
            if lo > 0:
                gains.append(key)
            if hi < 0:
                losses.append((key, point, lo, hi))
        ap = paired(label, 'ap')
        passes = (('ap' in gains or 'M' in gains) and not losses)
        loss_text = ('; '.join(f'Δ{k} {p:+.3f} [{lo:+.2f}–{hi:+.2f}]'
                               for k, p, lo, hi in losses)
                     if losses else 'no significant losses')
        lines.append(
            f'- **{label}**: ΔAP {ap[0]:+.4f} [{ap[1]:+.2f}–{ap[2]:+.2f}]; '
            f'significant gains: {", ".join(gains) if gains else "none"}; '
            f'{loss_text} — the shipping rule is '
            + ('**PASSED**.' if passes else 'not met.'))
    lines += ['',
              '_The v6l_novjump / v6l_thin rows are attribution (§6), '
              'not shippable forms; read their Δ as the contribution of the vjump '
              'family and of the cluster features respectively._', '']

    text = '\n'.join(lines)
    print(text)
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'written to {args.out}')


if __name__ == '__main__':
    main()
